const localBiblio = {
  FactDAG: {
    title:
      "FactDAG: Formalizing Data Interoperability in an Internet of Production",
    href: "https://doi.org/10.1109/JIOT.2020.2966402",
    publisher: "IEEE Internet of Things Journal, vol. 7, no. 4, pp. 3243-3253",
    date: "April 2020",
    status: "Research Paper",
    authors: [
      "Lars Gleim",
      "Jan Pennekamp",
      "Martin Liebenberg",
      "Melanie Buchsbaum",
      "Phillip Niemietz",
      "Simon Knape",
      "Alexander Epple",
      "Daniel Trauth",
      "Thomas Bergs",
      "Christian Brecher",
      "Stefan Decker",
      "Gerhard Lakemeyer",
      "Klaus Wehrle",
    ],
  },
  "SECURITY-VOCABULARY": {
    title: "The Security Vocabulary",
    href: "https://w3c-ccg.github.io/security-vocab/",
    authors: ["Manu Sporny", "Orie Steele", "Tobias Looker"],
    status: "CGDRAFT",
    publisher: "Credentials Community Group",
  },
  "LD-PROOFS": {
    title: "Linked Data Proofs 1.0",
    href: "https://w3c-ccg.github.io/ld-proofs/",
    authors: ["Dave Longley", "Manu Sporny"],
    status: "CGDRAFT",
    publisher: "W3C Digital Verification Community Group",
  },
  URDNA2015: {
    title: "RDF Dataset Normalization",
    href: "https://json-ld.github.io/rdf-dataset-canonicalization/spec/",
    authors: ["Dave Longley", "Manu Sporny"],
    status: "CGDRAFT",
    publisher: "Credentials W3C Community Group",
  },
  "OEZER-TRUST": {
    title:
      "Establishing Trust and Trustworthiness for Supply Chain Information Sharing",
    href: "https://doi.org/10.1007/978-3-319-32441-8_14",
    authors: ["Özalp Özer, Yanchong Zheng"],
    status: "Research Paper",
    date: "2017",
    publisher: "Handbook of Information Exchange in Supply Chain Management. Springer Series in Supply Chain Management, vol 5. Springer, Cham",
  },
  ReShare: {
    title:
      "Data Reliability and Trustworthiness Through Digital Transmission Contracts",
    href: "https://doi.org/10.1007/978-3-030-77385-4_16",
    authors: [
      "Simon Mangel",
      "Lars Gleim",
      "Jan Pennekamp",
      "Klaus Wehrle",
      "Stefan Decker",
    ],
    status: "Research Paper",
    date: "2021",
    publisher: "The Semantic Web. ESWC 2021. Lecture Notes in Computer Science, vol 12731. Springer, Cham",
  },
  TowardsIoP: {
    title: "Towards an Infrastructure Enabling the Internet of Production",
    authors: [
      "Jan Pennekamp",
      "René Glebke",
      "Martin Henze",
      "Tobias Meisen",
      "Christoph Quix",
      "Rihan Hai",
      "Lars Gleim",
      "Philipp Niemitz",
      "Maximilian Rudack",
      "Simon Knape",
      "Alexander Epple",
      "Daniel Trauth",
      "Uwe Vroomen",
      "Thomas Bergs",
      "Christian Brecher",
      "Andreas Bührig-Polaczek",
      "Matthias Jarke",
      "Klaus Wehrle",
    ],
    href: "https://doi.org/10.1109/ICPHYS.2019.8780276",
    status: "Research Paper",
    date: "2019",
    publisher:
      "2019 IEEE International Conference on Industrial Cyber Physical Systems (ICPS)",
  },
  "JSON-SCHEMA-VALIDATION": {
    authors: ["Austin Wright", "Henry Andrews", "Ben Hutton"],
    href: "https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation",
    publisher: "Internet Engineering Task Force (IETF)",
    status: "Internet-Draft",
    title:
      "JSON Schema Validation: A Vocabulary for Structural Validation of JSON",
    repository: "https://github.com/json-schema-org/json-schema-spec",
    id: "json-schema-validation",
    date: "11 June 2021",
  },
};
