name: Build and Deploy to GitHub pages
on: [push]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          sudo npm i -g less respec

      - name: Make Widoco documentation
        run: make

      # This does not work at the moment, TODO possibly fix in future
      # For now, we should run 'make respec-snapshot' locally before committing.
      #- name: Make ReSpec snapshot
      #  run: |
      #    make respec-snapshot
      #    mv public/index-snapshot.html public/index.html
      # Instead, now we simply remove the source page
      - name: Remove source HTML
        run: rm public/index-src.html

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
